# fly.toml app configuration file generated for buildui-work-journal on 2023-10-31T11:34:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "buildui-work-journal"
primary_region = "ewr"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false
